CREATE TABLE TB_ENTITY_TEST(
Id number,
Name VARCHAR2(50),
StartDate TIMESTAMP
);

--DROP TABLE TB_ENTITY_TEST;

SELECT * FROM TB_ENTITY_TEST;
INSERT INTO TB_ENTITY_TEST (Id, Name, StartDate) VALUES ('1','Teste 1 via banco','03/09/2023');
INSERT INTO TB_ENTITY_TEST (Id, Name, StartDate) VALUES ('2','Teste 2 via banco','03/09/2023 00:47:01');
INSERT INTO TB_ENTITY_TEST (Id, Name, StartDate) VALUES (3,'Teste 3 via banco','03/09/2023');
INSERT INTO TB_ENTITY_TEST (Id, Name, StartDate) VALUES ('4','Teste 4 via banco','03/09/2023 22:09');
INSERT INTO TB_ENTITY_TEST (Id, Name, StartDate) VALUES ('5','Teste 5 via banco','03/09/2023 22:09:00');
INSERT INTO TB_ENTITY_TEST (Id, Name, StartDate) VALUES ('6','Teste 6 via banco','03/09/23 22:10:00');
--DELETE FROM TB_ENTITY_TEST;

COMMIT;

SELECT * FROM "SYSTEM".TB_ENTITY_TEST WHERE Id = 1;
SELECT * FROM TB_ENTITY_TEST WHERE (1 = 1);

SELECT
    OWNER,
    OBJECT_NAME,
    OBJECT_TYPE
FROM
    ALL_OBJECTS
WHERE
    OBJECT_NAME = 'TB_ENTITY_TEST';



CREATE TABLE TEST.TB_ENTITY_TEST
(
    Id NUMBER PRIMARY KEY,
    Name NVARCHAR2(4000),
    StartDate TIMESTAMP,
    TestDouble NUMBER,
    TestBoolean NUMBER(1)
);